### ISSUE TITLE
Add GitHub links handling

### ISSUE THREAD

**Issue by BobbyESP** [FluentHub/FluentHub#122]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### Description

This would make the app able to open GitHub links in the app instead of the internet browser

**Comment by onein528** [comment]
This feature is one of the most important. I would like to parameterize the URL when I click on a tree or blob item in the repository or when I click on some button and navigate. do so, more confotable when navigate page.

**Comment by onein528** [comment]
and we need to create hander and parser

**Comment by onein528** [comment]
We need to discuss how to implement this. I have an idea, but @luandersonn has better than mine, maybe.

**Comment by luandersonn** [comment]
> We need to discuss how to implement this. I have an idea, but @luandersonn has better than mine, maybe.

UWP has an API for this. https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking

**Comment by onein528** [comment]
Yea. good. but problem is how parse the url user gave: when user enter the specific url, we need to discuss how to navigate page

**Comment by DeveloperWOW64** [comment]
This feature just *might* conflict with GU11

**Comment by BobbyESP** [comment]
Yeah, we'll take a look to this in future updates.

**Comment by BobbyESP** [comment]
Maybe we need a roadmap

**Comment by BobbyESP** [comment]
In trello or something like that

**Comment by DeveloperWOW64** [comment]
We can use GH Projects or MS loop but thats still in dev

**Comment by onein528** [comment]
this feature is developing on multi-account support PR.

**Comment by onein528** [comment]
@DeveloperWOW64 Why might be conflict?

**Comment by DeveloperWOW64** [comment]
> @DeveloperWOW64 Why might be conflict?

Remember this conversation?
![image](https://user-images.githubusercontent.com/71598437/172048667-f1b4efe2-fa71-49a2-b9cd-8c841b193e25.png)
I added it in GU11

**Comment by onein528** [comment]
Yes. but then how do we implement how to navigate.

**Comment by DeveloperWOW64** [comment]
> Yes. but then how do we implement how to navigate.

Yeah thats the problem

**Comment by onein528** [comment]
Since the implementation in GU10 is almost complete, would you please stop the implementation of the simplified URL in GU11? I may notice it when implementing that in repository pages.

**Comment by DeveloperWOW64** [comment]
> Since the implementation in GU10 is almost complete, would you please stop the implementation of the simplified URL in GU11? I may notice sth when implementing that in repository pages.

Ooohh thats going to be difficult.
Are you sure GH links handling will fail?
We could make a converter that converts GH links to FH readable links

Url element = actual gh url
displayurl = readable url

**Comment by onein528** [comment]
There is a great deal of concern about conflicts when General Updates are rife,

**Comment by DeveloperWOW64** [comment]
Mm yes. What do you meant though when you say 'implememtation in GU10 is almost complete'

**Comment by onein528** [comment]
Until now, all pages related to the repository code have a ViewModel called RepoContextViewModel that holds the information that the URL has, such as the owner name, repository name, and default branch name, and passes it when navigating.　

However, in GU10, I am planning to implement a model called NavigateInfoModel that holds the URL and passes it during navigation.

![image](https://user-images.githubusercontent.com/62196528/172050118-c2e5da3d-04b9-4a12-a371-4d4799a9f02f.png)

**Comment by DeveloperWOW64** [comment]
I thought you abandoned GU10

**Comment by onein528** [comment]
Yes. but this'll be GU10 https://github.com/FluentHub/FluentHub/pull/127 . that's reason why I asked you to change your branch name.

**Comment by onein528** [comment]
How to pass arguments when linking or navigating is a very serious problem. I think we need to discuss it very deeply.

**Comment by DeveloperWOW64** [comment]
> How to pass arguments when linking or navigating is a very serious problem. I think we need to discuss it very deeply.

Okay. I can make a discord voice/text/gh discussion for it?

**Comment by DeveloperWOW64** [comment]
Which one?

**Comment by onein528** [comment]
text one

**Comment by DeveloperWOW64** [comment]
> text one(cannot speak fluently hahaa)

🙃 https://discord.com/channels/935562861701390336/982985508634366002

**Comment by onein528** [comment]
On going feature. no end.

**Comment by DeveloperWOW64** [comment]
> On going feature. no end.

@onein528 WDYM?

**Comment by onein528** [comment]
I created handling methods so completed feature

**Comment by DeveloperWOW64** [comment]
> I created handling methods so completed feature

In GU12?

**Comment by onein528** [comment]
No, in GU11. please take a look at OnNavigatedTo in DetailsLayoutModePage.xaml.cs

**Comment by onein528** [comment]
parsing URL.
