### ISSUE TITLE
Users have unformatted icons

### ISSUE THREAD

**Issue by DeveloperWOW64** [FluentHub/FluentHub#146]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

0.3.0.0 | X64 | DEBUG

### Description

(for me, at least) 
My user icon in the top right is not formatted to display correctly in the circle.

### Expected behavior

Should be formatted to fit in the circle as a full icon

### Relevant Assets

![image](https://user-images.githubusercontent.com/71598437/169645445-a4b49c45-f789-4e81-a64f-bf876e80dccd.png)

**Comment by onein528** [comment]
I will fix this issue on #137

**Comment by onein528** [comment]
can you check if this issue was solved by GU9?

**Comment by DeveloperWOW64** [comment]
> can you check if this issue was solved by GU9?

sure

**Comment by nathayoung** [comment]
> can you check if this issue was solved by GU9?

Looks like it's fixed in gu9: 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/46688736/169670852-26bcdfff-5797-4fd4-b383-50bc7a455472.png">

**Comment by onein528** [comment]
Nice!
