### ISSUE TITLE
Errors with e6f128a

### ISSUE THREAD

**Issue by DeveloperWOW64** [FluentHub/FluentHub#156]
### Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 11

### What version/architecture of FluentHub are you on?

DEBUG on x64, 0.3.0

### Description

Commit e6f128a80ae7d25271859476c7a6aedc3bac2f10 on #155 causes errors with FluentHub.Octokit that prevents build in VS.

### Expected behavior

Should build properly and easily.

### Relevant Assets

![image](https://user-images.githubusercontent.com/71598437/169970410-d34aec33-b10b-4326-af4f-206b912fa9cd.png)

**Comment by onein528** [comment]
This is because if your precious changes?

**Comment by onein528** [comment]
I merged unbuildable changes... sorry.
