### ISSUE TITLE
Markdown formatting

### ISSUE THREAD

**Issue by DeveloperWOW64** [FluentHub/FluentHub#174]
### Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### Description

Various changes to make README formatting more fluent:

1. Text written
> (`>`) with this style

should use InfoBar:

No InfoBar:
![image](https://user-images.githubusercontent.com/71598437/172013783-5e6ab3f2-97c0-420b-8b12-a8dd98b0541b.png)
InfoBar:
![image](https://user-images.githubusercontent.com/71598437/172013912-e49615f9-279c-4312-afc0-01777336c746.png)
~ it could have an `x` button to close it.

2. Hyperlink button
On headers, there is a hyperlink button.
However, the icon for this is hidden slightly and looks ugly.
![image](https://user-images.githubusercontent.com/71598437/172014384-aefc6e55-7e12-48e0-89b8-384769e06657.png)
As well as this, the button itself is pretty useless.

**Comment by onein528** [comment]
used in the README are HTML and CSS.

**Comment by DeveloperWOW64** [comment]
> used in the README are HTML and CSS.

Oh so its just previewed with web and not actually involved with FH?

**Comment by onein528** [comment]
This CSS has been a problem for some time. But once it was closed because we didn't think we could make something better than the current UI. https://github.com/FluentHub/FluentHub/issues/58

**Comment by onein528** [comment]
> Oh so its just previewed with web and not actually involved with FH?

Yes. just borrowed from github-markdown-css

**Comment by DeveloperWOW64** [comment]
Ohh. Can we use custom CSS?

**Comment by onein528** [comment]
There is the idea of using MarkdownBlock or RichTextBlock, but I feel it should be discussed.

**Comment by onein528** [comment]
> Ohh. Can we use custom CSS?\

Of course.

**Comment by onein528** [comment]
https://github.com/FluentHub/FluentHub/tree/main/src/FluentHub/Assets/WebView

**Comment by DeveloperWOW64** [comment]
https://unpkg.com/fluent-svelte/theme.css

Maybe this will work?

**Comment by onein528** [comment]
should be. this css just declare variables

**Comment by onein528** [comment]
> Ok, i need to see the libraty, but this is gonna be hard. Fluent Svelte is like a framework and we need to take a look to how it works

@BobbyESP He has said previously.

**Comment by DeveloperWOW64** [comment]
> > Ok, i need to see the libraty, but this is gonna be hard. Fluent Svelte is like a framework and we need to take a look to how it works
> 
> @BobbyESP He has said previously.

when?

**Comment by onein528** [comment]
https://github.com/FluentHub/FluentHub/issues/58#issuecomment-1045976174

**Comment by onein528** [comment]
Woow, nicee!

**Comment by onein528** [comment]
This app uses GitHub v3 Markdown API. but If we would like to use fluent-svelte style sheets, maybe this will be helpful. https://github.com/pablo-abc/svelte-markdown Do you @DeveloperWOW64 other than?

**Comment by onein528** [comment]
And we need to discuss alternative ways. WebView is very heavy. when use many times, it takes long time to load page. RichTextBlock may be still good way.

**Comment by DeveloperWOW64** [comment]
> Do you @DeveloperWOW64 other than?

WDYM?

**Comment by onein528** [comment]
Do you know other than i told you?

**Comment by DeveloperWOW64** [comment]
> Do you know other than i told you?

Other MD css sheets?
If so, there's two good ones I found:
https://github.com/markdowncss/air
https://github.com/jasonm23/markdown-css-themes
https://takosthings.github.io/Fluent-Discord/Fluent-Discord.css

**Comment by onein528** [comment]
no. I really want to use fluent-svelte's stylesheet. so i thought we need a markdown parser for svelte in order to.

**Comment by onein528** [comment]
alt: maybe we should even create our own

**Comment by onein528** [comment]
but, at the point of view of the app performance, do not like to use WebView.

**Comment by onein528** [comment]
yes. and I have 3 ways to display markdown.

Way|good|bad
---|---|---
WebView -> Svelte -> fluent-svelte | very customizable | heavy
MarkdownTextBlock -> original resourcec dictionaryb | discustomizable | light-weight
RichTextBlock -> original user control | discostomizable | light-weight and can be fluent looks

If we will go with 1, we need a renderer for svelte

For example, 
https://github.com/pablo-abc/svelte-markdown
https://github.com/ssssota/svelte-exmarkdown

**Comment by DeveloperWOW64** [comment]
> For example, https://github.com/ssssota/svelte-exmarkdown

The Files website used to use MDSVEX which is svelte-exmarkdown's predecessor

**Comment by onein528** [comment]
> maybe we should even create our own
And also, our own css can be good.

**Comment by onein528** [comment]
> The Files website used to use MDSVEX which is svelte-exmarkdown's predecessor

We can use that? actually, i dont know about svelte.

**Comment by DeveloperWOW64** [comment]
> > The Files website used to use MDSVEX which is svelte-exmarkdown's predecessor
> 
> We can use that? actually, i dont know about svelte.

Maybe.. 1 is definitely the  best option

**Comment by onein528** [comment]
okay let's go on. other github client app also use this option like JitHub, CodeHub.

**Comment by onein528** [comment]
This should be fixed already.

Alternative solution

- Use WebView2 for stability
- Use MarkdownTextBlock
- Use RichTextBlock with ourown GMF parser

All of them are withdrawn.

**Comment by DeveloperWOW64** [comment]
> All of them are withdrawn.

@onein528 WDYM by 'withdrawn'? How is it fixed already?

**Comment by onein528** [comment]
'Not able to do'. All of them could not be implemented.
