### ISSUE TITLE
Back/Forward navigation does not work properly

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#184]
### Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 11

### What version/architecture of FluentHub are you on?

0.3.0

### Description

As the title.
It appears that the navigation history is not properly stored in the stack when a frame other than the main frame is navigated.

### Steps To Reproduce

1. Go to repo code content sub dir several times.
2. Go back.
3. See what's happeing.

### Expected behavior

Correctly back/forward

**Comment by onein528** [comment]
@luandersonn Hi. How have you been?

**Comment by luandersonn** [comment]
@onein528 In my tests it is working correctly.

**Comment by onein528** [comment]
No way...

**Comment by onein528** [comment]
@luandersonn DO contribute something. You are same as code owner of FH navigation system and please maintain and adapt.

When navigating a sub frame, cannot back/forward by using back/forward buttons (repo code -> issues oage -> back to repo code page using back button does not work properly).

**Comment by luandersonn** [comment]
> When navigating a sub frame, cannot back/forward by using back/forward buttons (repo code -> issues oage -> back to repo code page using the back button does not work properly).

Okay, I'll check

**Comment by onein528** [comment]
### The Fact

Currently, the main frame displays the repository's overview page and its subframes display issues, PR, and other pages.

### What's problem?

When a URL is passed, the page is navigated, but it is not stored correctly on the stack. This is because frame information is only saved when navigationservice.navigate is used.

### New idea

Overview on above will be added as user control each page.

```xaml
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>

    <uc:RepositoryOverview ViewModel="{x:Bind ViewModel.RepositoryOverviewVM, Mode=OneWay}" />

    <Grid>
        ....
    </Grid>
</Grid>
```

![image](https://user-images.githubusercontent.com/62196528/180608471-7bd0ebd5-a55f-466d-a627-83ee61ac029c.png)
