### ISSUE TITLE
Improve security of the authorization phase

### ISSUE THREAD

**Issue by DeveloperWOW64** [FluentHub/FluentHub#186]
### Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 11

### What version/architecture of FluentHub are you on?

DEBUG x64

### Description

I have an interesting theory:
Why don't we use the GH developer app for FH like we have used to on the store and delete AppCredentials.config so we can have a universal API key. This would remove the unnecessary method of the user creating an app and creating and entering the details in AppCredentials.config.
I would wish to try this, though it may cause security vulnerabilities that I have overlooked.

**Comment by DeveloperWOW64** [comment]
@onein528 what do you think?

**Comment by onein528** [comment]
What's the GitHub Developer App? Are you going to say "GitHub Apps"?

**Comment by DeveloperWOW64** [comment]
> 

yes

**Comment by DeveloperWOW64** [comment]
I'll just test on a new PR with head branch GU12

**Comment by onein528** [comment]
in this org, named "FluentHub-Credentials" repo.

**Comment by onein528** [comment]
I am now in school.

**Comment by onein528** [comment]
@DeveloperWOW64 Can you try this?

Just checking. You wanna use GitHub Apps not OAuth? and it can be useful?

**Comment by onein528** [comment]
But do not create GU13 until been merged GU12 not to make conflicts please.

**Comment by DeveloperWOW64** [comment]
> But do not create GU13 until been merged GU12 not to make conflicts please.

okay.
