### ISSUE TITLE
Implementation of IncrementalLoading

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#189]
### Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### Description

As the title

**Comment by DeveloperWOW64** [comment]
@onein528 What is IncrementalLoading?

**Comment by onein528** [comment]
When scrolled to the end, request more items. Don't need to get all data. By doing so, I can get each 100 or sth items.

**Comment by DeveloperWOW64** [comment]
When do you plan to implement this? @onein528

**Comment by onein528** [comment]
Yes. wait a week.

**Comment by DeveloperWOW64** [comment]
> Yes. wait a week.

ahh of exams, i get it
