### ISSUE TITLE
[Internal] Test for issue template

### ISSUE THREAD

**Issue by DeveloperWOW64** [FluentHub/FluentHub#198]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

test

**Comment by onein528** [comment]
@DeveloperWOW64 why did you create this?

**Comment by DeveloperWOW64** [comment]
> @DeveloperWOW64 why did you create this?

Ahh.. needed to test what the Markdown looked like for the issue template.. nvm
