### ISSUE TITLE
An exception from LoadActivitiesAsync() occur in loading user home page in the Store released app

### ISSUE THREAD

**Issue by hunterlan** [FluentHub/FluentHub#210]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11

### 🔢 What version/architecture of FluentHub are you on?

0.3.30.0 | X64 | RELEASE

### 📄 Description

Program crashes on opening page "Home".

Also, if you straight away click to profile, program will not crush, until you back to page "Home".

### 🪜 Steps To Reproduce

1. Launch FluentHub.
2. Waiting for starting load page.
3. See, how FluentHub unexpectedly closed.

### 🤔 Expected behavior

Expected to see information on page "Home", and FluentHub will not closed by exception. 

### 📸 Assets

Can't provide logs, because button, which should open log file or path to log file doesn't work :(

**Comment by onein528** [comment]
I want to let you know: publishing the app to the Store is the first time I've solved Linq, which has been the biggest problem in our community for a long time.

What all I need is log, please open `C:\Users\[USERNAME]\AppData\Local\Packages\FluentHubDev_9es9q7t8fr9b8\LocalState\FluentHub.Logs` and please show me.

**Comment by hunterlan** [comment]
[Log20220726.log](https://github.com/FluentHub/FluentHub/files/9188766/Log20220726.log)
@onein528 here it is. I understand that developing is difficult as a programmer. Maybe, may I help to develop program?

**Comment by onein528** [comment]
I did see the log. According to it, you seem to click "See feeds" on Home page, right?

> Maybe, may I help to develop program?

Definitely of course! that's a greate honor!

**Comment by hunterlan** [comment]
> I did see the log. According to it, you seem to click "See feeds" on Home page, right?

No, I just launched program, and then it crashes. But, maybe it logged situation, when I was in time and click to "Profile", and then, click other pages. Wanted to see what implemented 😅

**Comment by onein528** [comment]
```
2022-07-26 11:31:50.048 +02:00 [ERR] LoadActivitiesAsync
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentHub.Octokit.Wrappers.ActivityWrapper.Wrap(IReadOnlyList`1) + 0x179
   at FluentHub.Octokit.Queries.Users.ActivityQueries.<GetAllAsync>d__0.MoveNext() + 0x156
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at FluentHub.Uwp.ViewModels.Home.ActivitiesViewModel.<LoadActivitiesAsync>d__14.MoveNext() + 0x345

```

When launched the app, `LoadActivitiesAsync` should not be called actually. Had you clicked "activities" button on the sidenavigation really?

**Comment by hunterlan** [comment]
No, I didn't. I can send you a video

**Comment by onein528** [comment]
Looking forward to see that.

**Comment by hunterlan** [comment]
> Looking forward to see that.

https://user-images.githubusercontent.com/38838841/181012498-2d95e117-0720-4489-858c-fd11508c9f00.mp4

**Comment by onein528** [comment]
Weird. Could not possible. but I know activities page has bugs and have to fix it immediately. Thank you for reporting this. I'll work on this.

By the way, you can build this project?

**Comment by hunterlan** [comment]
> By the way, you can build this project?

Doing this right now.

**Comment by hedhehd** [comment]
That's exactly what's happening to me in microsoft store version..

**Comment by hunterlan** [comment]
> Weird. Could not possible

Agree with you, because I've built it, and it works normally (if I won't mention "Activity" of course 😅)

**Comment by onein528** [comment]
This issue have been fixed already.
