### ISSUE TITLE
The value passed to Single was null

### ISSUE THREAD

**Issue by NoobNotFound** [FluentHub/FluentHub#212]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11 Dev

### 🔢 What version/architecture of FluentHub are you on?

0.3.30.0 | X64 | RELEASE

### 📄 Description

I just went to my repository named Noobsenger and this happened. The Fluenthub didn't load the source files except the ReadMe.md. This happened to me sometimes in other repositories too...

### 🪜 Steps To Reproduce

1. Go to a some kind of repository (mine: Noobsenger).
2. You can see the error/exception right down the tab bar
(only sometimes)

### 🤔 Expected behavior

Load the source code correctly.

### 📸 Assets
![image](https://user-images.githubusercontent.com/82730163/181264719-94d6530b-d71b-412f-8773-66c79e32e99d.png)

[Log20220727.log](https://github.com/FluentHub/FluentHub/files/9199512/Log20220727.log)

**Comment by onein528** [comment]
it happens in GetWithObjectNameAsync() and there's one Single() using:

![image](https://user-images.githubusercontent.com/62196528/181267404-c422df85-a7f6-45e8-8135-3c312c79442f.png)

Deleted user? maybe. I will convert to SingleOrDefault()

**Comment by hunterlan** [comment]
@onein528 the commit af209cb4 fixed this issue, right?
