### ISSUE TITLE
Add contribution graph to user overview page

### ISSUE THREAD

**Issue by hunterlan** [FluentHub/FluentHub#213]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

Every user, who has a little activity on GitHub, has this thing. 

### 📸 Assets

![image](https://user-images.githubusercontent.com/38838841/181272764-b2685b6c-75b2-488c-91dd-43a174786814.png)

**Comment by onein528** [comment]
Actually the app had this feature, but currently disabled and it will be enabled soon.

![image](https://user-images.githubusercontent.com/62196528/181346431-c9e67634-2a6d-4532-ab76-16d2d56488c7.png)

**Comment by hunterlan** [comment]
> Actually the app had this feature, but currently disabled and it will be enabled soon.
> 

Oh, didn't know about it, sorry :D But you can use this issue, when it will be enabled

**Comment by onein528** [comment]
@hunterlan I fix this issue pre v0.3.7

**Comment by hunterlan** [comment]
> @hunterlan I fix this issue pre v0.3.7

You mean when you will release v0.3.7?

**Comment by onein528** [comment]
Yes

**Comment by DeveloperWOW64** [comment]
@onein528 Isn't this fixed in 98de5119a0ab4e9e39fb429dcf07ce3f385070e8?

**Comment by onein528** [comment]
Oh yeah. Thanks
