### ISSUE TITLE
Implement editing basic user information

### ISSUE THREAD

**Issue by hunterlan** [FluentHub/FluentHub#215]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

Now, you can click and see the window, like on picture 1, but you can't close it and also you can't see, what fields are filled already. 
Should be implemented like on picture 2

### 🗃️ Alternative solutions

1. Get user info, and show information in fields
2. Add scroll bar
3. Add button "Close" 

### 📸 Assets

![image](https://user-images.githubusercontent.com/38838841/181442284-cd9258ea-220c-4746-8dbf-549770210c0c.png)
Picture 1 - Current implementation in FluentHub
![image](https://user-images.githubusercontent.com/38838841/181442401-49b3d898-2f10-4e19-ad60-1eb008acad79.png)
Picture 2 - Reference, how it should be implemented, website GitHub.

**Comment by onein528** [comment]
Thank you for requesting new features! If you don't mind requesting ideas other than those existing GitHub features, please do.

**Comment by hunterlan** [comment]
> If you don't mind requesting ideas other than those existing GitHub features, please do.

I will. And if I can, I will implement these ideas :)

**Comment by onein528** [comment]
Ye, please!

**Comment by onein528** [comment]
Tracking in #253

**Comment by onein528** [comment]
Tracking on #253
