### ISSUE TITLE
Implement repository settings page

### ISSUE THREAD

**Issue by hunterlan** [FluentHub/FluentHub#217]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

It has a page, but hasn't functionality.

### 📸 Assets

![image](https://user-images.githubusercontent.com/38838841/181481472-b4c765f7-64d0-406a-883c-5456c8f27743.png)
Picture 1 - current settings
![image](https://user-images.githubusercontent.com/38838841/181481524-3db15a34-f600-461c-81ec-4d5e2fff3431.png)
Picture 2 - settings should be

**Comment by onein528** [comment]
Tracking in #253

**Comment by onein528** [comment]
Tracking on #253
