### ISSUE TITLE
Help for translating

### ISSUE THREAD

**Issue by HelderRocket** [FluentHub/FluentHub#219]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

I would like to help translating this application in my native language (in this case, Spanish), Is there any way I can help with that?

PS: I commented about your project on the official "UWP Community" channel, I would advise to check that further.
![image](https://user-images.githubusercontent.com/104467221/181799516-213e3e16-965b-4d4b-ad98-73b2a48e0ba2.png)

**Comment by onein528** [comment]
I'm preparing to translate with Crowdin but there'is no resources. it will take much time to add defaul strings.

https://crowdin.com/project/fluenthub

**Comment by senolfndk** [comment]
can you add turkish language

**Comment by hunterlan** [comment]
> It will take much time to add defaul strings.
> 
> https://crowdin.com/project/fluenthub

I can work with this issue. I've never worked with crowdin, but I have an experience with internalisation.

**Comment by hedhehd** [comment]
> can you add turkish language

I can speak turkish and german pretty good. But I don't know how to add a language in windows apps.

**Comment by onein528** [comment]
Hi, all!

I added popular languages. Please check [it](https://crowdin.com/project/fluenthub) out!!

**Comment by senolfndk** [comment]
> Herkese selam!
> 
> Popüler dilleri ekledim. Lütfen kontrol [edin](https://crowdin.com/project/fluenthub) !!

thank you for the turkish language

**Comment by DeveloperWOW64** [comment]
> I would like to help translating this application in my native language (in this case, Spanish)

@HelderRocket Once translation resources are possible. A member of our team (@BobbyESP) is native Galician and so will help us, however, as is usual with any regular open-source software, you can contribute as much as you like.
PS: I can actually understand Spanish too! But I'm not native like you are so it's pretty bad...

**Comment by HelderRocket** [comment]
@DeveloperWOW64 It's a bit confusing, but it seems (from what I understand from Wikipedia, that Galician is not Spanish, or not exactly (maybe it's like Latin Spanish and Sword Spanish, in other words, a lot of confusion even among us). 😅😅😅

**Comment by HelderRocket** [comment]
@DeveloperWOW64 If you like, you can add the two types of Spanish (ignoring of course the sub-varieties of Latin Spanish) and let the @BobbyESP  take care of the Spanish one, since I speak Latin Spanish, and if there is a big difference in both.

**Comment by onein528** [comment]
@DeveloperWOW64 We have to get started to adding new l10n resources. You have any acknowledge about it: you can addresiurces and make FluentHub be localizable?

**Comment by DeveloperWOW64** [comment]
> @DeveloperWOW64 We have to get started to adding new l10n resources. You have any acknowledge about it: you can addresiurces and make FluentHub be localizable?

You mean you want to make the resources usable? @onein528

**Comment by onein528** [comment]
Yep.

If there is localizable text block, I'd like you to add its resource and replace them to it. I will tell you first step by pushing new commit to main. just wait a hour

**Comment by DeveloperWOW64** [comment]
> Yep.
> 
> If there is localizable text block, I'd like you to add its resource and replace them to it. I will tell you first step by pushing new commit to main. just wait a sec

lool @onein528 ~~it probably made more sense when you said 'wait an hour'~~
but honestly no pressure, take your time mate.

**Comment by onein528** [comment]
Sorry. I immediately will do.

**Comment by onein528** [comment]
Done. I'm building now.

**Comment by DeveloperWOW64** [comment]
> Yep.
> 
> If there is localizable text block, I'd like you to add its resource and replace them to it. I will tell you first step by pushing new commit to main. just wait a sec

Sorry I don't have enough time to do that today.. I will tomorrow.

**Comment by onein528** [comment]
Now, Crowdin has been alredy set up and if you would like to translate the project, you can visit [our Crowdin page](https://crowdin.com/project/fluenthub) without any local forks for this purpose.

**Comment by onein528** [comment]
Thank you for your contributions anytime.
