### ISSUE TITLE
FluentHub Identity

### ISSUE THREAD

**Issue by DeveloperWOW64** [FluentHub/FluentHub#224]
### ⏱️ Before you start...

- [X] Have you checked if a similar tracker has already been reported?

### 🛤️ Feature

 - [x] App Name
 - [x] App Description
 - [x] App Versions
 - [x] Legal Identity
 - [x] Social Media
### 📄 Description

There are parts of FluentHub's identity that need to be clarified and decided. See the list above.

**Comment by DeveloperWOW64** [comment]
@onein528 We also need to think about FluentHub's description. There are multiple across different sites, so it's difficult to keep track of them:
Website: A stylish yet wonderfully powerful GitHub Oauth client
GitHub: A fluent yet powerful GitHub Oauth client app for Windows
GitHub Organisation: Making the best GitHub client for windows
My idea (also Twitter): A stylish yet powerful GitHub client
What do you think? If you have a different idea, feel free to tell me!

**Comment by onein528** [comment]
Your idea.

**Comment by DeveloperWOW64** [comment]
Now we need to discuss app versions. I don't think we need to have all channels:
Stable, Beta, Dev, Can so can we limit it to 2 or so. e.g. Stable & Beta. We could do more, but it would be harder to keep track of and update. I think we should do Stable and Dev. @onein528

**Comment by onein528** [comment]
I have light green. So I ask creator if can he change color to beta coloring - blue.

**Comment by DeveloperWOW64** [comment]
> I have light green. So I ask creator if can he change color to beta coloring - blue.

What do you mean?

**Comment by onein528** [comment]
Dev icon have a green label. But I don't like a logo with green coloring. So I'd like to change green I blue.

**Comment by onein528** [comment]
What do you mean by Legal identity?

**Comment by DeveloperWOW64** [comment]
> What do you mean by Legal identity?

@onein528 What is the name of the FluentHub group?
(c) FluentHub/ FluentHub Team etc.

**Comment by onein528** [comment]
Ah,

(c) 2022 FluentHub
(c) 2022 FluentHub Team
(c) 2022 FluentHub Community

I don't know it's a good idea to add year.

**Comment by DeveloperWOW64** [comment]
> I don't know it's a good idea to add year.

Yes @onein528 You should add year. But when it comes to later years e.g. 2023 It will need to be 2022-2023.
But which one do you think? the org nickname is now FluentHub Application Community so we could use that. Personally I think either 
a) FluentHub Community
b) FluentHub Team

**Comment by DeveloperWOW64** [comment]
> > I don't know it's a good idea to add year.
> 
> Yes @onein528 You should add year. But when it comes to later years e.g. 2023 It will need to be 2022-2023. But which one do you think? the org nickname is now FluentHub Application Community so we could use that. Personally I think either a) FluentHub Community b) FluentHub Team

@onein528

**Comment by onein528** [comment]
FluentHub Team, maybe.

**Comment by DeveloperWOW64** [comment]
> FluentHub Team, maybe.

GU16?

**Comment by onein528** [comment]
what do you mean?

**Comment by DeveloperWOW64** [comment]
> what do you mean?

Create it

**Comment by DeveloperWOW64** [comment]
> Dev icon have a green label. But I don't like a logo with green coloring. So I'd like to change green I blue.

So you'd like to keep only Stable and Dev? or all? What versions do you want to keep?

**Comment by DeveloperWOW64** [comment]
lol
![image](https://user-images.githubusercontent.com/71598437/183893215-5c7ec7c9-8ac4-4903-9591-8d3970d583d9.png)

**Comment by DeveloperWOW64** [comment]
> > Dev icon have a green label. But I don't like a logo with green coloring. So I'd like to change green I blue.
> 
> So you'd like to keep only Stable and Dev? or all? What versions do you want to keep?

@onein528

**Comment by onein528** [comment]
yea currently working on issue event items. so need various events.

**Comment by onein528** [comment]
> > > Dev icon have a green label. But I don't like a logo with green coloring. So I'd like to change green I blue.
> > 
> > 
> > So you'd like to keep only Stable and Dev? or all? What versions do you want to keep?
> 
> @onein528

IDK... stable or dev / stable or beta would be great

**Comment by DeveloperWOW64** [comment]
> > > > Dev icon have a green label. But I don't like a logo with green coloring. So I'd like to change green I blue.
> > > 
> > > 
> > > So you'd like to keep only Stable and Dev? or all? What versions do you want to keep?
> > 
> > 
> > @onein528
> 
> IDK... stable and dev / stable and beta would be great

Stable and dev then

**Comment by onein528** [comment]
but do you like green?

![image](https://user-images.githubusercontent.com/62196528/183893629-5d01c895-2c42-4f3d-a8e4-691411a058f9.png)

**Comment by DeveloperWOW64** [comment]
> but do you like green?

yes.

**Comment by onein528** [comment]
then, go ahead.

**Comment by onein528** [comment]
I wanna change...

I told you I wanna use dev/stable for now before, but it seems that dev/beta is better, I suppose. And when v1 use dev/stable. How do you say?

**Comment by onein528** [comment]
@DeveloperWOW64

**Comment by DeveloperWOW64** [comment]
> I wanna change...
> 
> I told you I wanna use dev/stable for now before, but it seems that dev/beta is better, I suppose. And when v1 uses dev/stable. What do you say?

As in dev/beta/stable? Well, why? It looks nice on paper, but I don't think it'll work in practice. We'll need to implement many different things. There is a way we could do it:
3 branches:
stable (main): updated every new release
beta: beta channel
dev: dev channel
Fresh GUs will be uploaded to dev and so will other updates. after at least one gu in dev, dev will merge with beta. After beta has 5 GUs, beta merges with dev. OFC we could edit this system (lol i just invented it), but we can see how it plays out first. @onein528 What do you think?

**Comment by onein528** [comment]
No. Just bed/beta for now. And when achieved to v1, use dev/stable. That's my concept.

**Comment by DeveloperWOW64** [comment]
> No. Just dev/beta for now. And when achieved to v1, use dev/stable. That's my concept.
> 
> Former: for the GitHub(debug mode) Latter: for the store(release mode)

yes that's what i thought as well.. Good.
