### ISSUE TITLE
App icon is not displayed in the title grid and intro page

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#229]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11, Windows 11 Dev

### 🔢 What version/architecture of FluentHub are you on?

0.3.5 | RELEASE

### 📄 Description

As the title.
Should be fixed in GU17.

### 🪜 Steps To Reproduce

1. Just open app

### 🤔 Expected behavior

Displayed correctly

### 📸 Assets

![image](https://user-images.githubusercontent.com/62196528/183895445-836c2ab4-ed0e-48d7-9a0a-3fdb9ea8e867.png)

**Comment by DeveloperWOW64** [comment]
@onein528 I've had this issue before.

**Comment by onein528** [comment]
I may have to use muxc:ImageIcon.

**Comment by onein528** [comment]
I did figure out. This problem is caused by wrong path specification.

Currently: /Assets/AppTiles/...

Should be: ms-appx:///Assets/AppTiles/...
