### ISSUE TITLE
Add primer control AvatarStack and AvatarPair

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#236]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

- Related #231 

**primer react `AvatarPair` https://primer.style/react/AvatarPair**

![image](https://user-images.githubusercontent.com/62196528/185953648-f4b9da11-2081-4f2f-9ee3-82402985a190.png)

**primer react `AvatarStack` https://primer.style/react/AvatarStack**

![image](https://user-images.githubusercontent.com/62196528/185953748-fe219fe8-30c8-4465-aca8-087939b431d7.png)

| Capability | Priority |
| :---------- | :------- |
| Adding primer control `AvatarPair` | Should |
| Adding primer control `AvatarStack` | Should |

**Comment by onein528** [comment]
Do you know slide animation or something like that? I'd like to implement animation: when I hover over the control, control be spread over the horizon. You can see this animation participants avatar pair control in GitHub notification page

**Comment by DeveloperWOW64** [comment]
> Do you know slide animation or something like that? I'd like to implement animation: when I hover over the control, control be spread over the horizon. You can see this animation participants avatar pair control in GitHub notification page

Ok.

**Comment by DeveloperWOW64** [comment]
> Do you know slide animation or something like that? I'd like to implement animation: when I hover over the control, control be spread over the horizon. You can see this animation participants avatar pair control in GitHub notification page

@onein528 This:
https://docs.microsoft.com/en-gb/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.animation.easingfunctionbase?view=windows-app-sdk-1.1

**Comment by onein528** [comment]
Thanks. I will learn about it.
