### ISSUE TITLE
Add user's popular repos and make repos pinnable

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#242]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

![image](https://user-images.githubusercontent.com/62196528/187145242-eb186de3-7028-48d4-beea-516a04443b6b.png)

### 🗃️ Alternative solutions

_None. Just implement_

**Comment by DeveloperWOW64** [comment]
@onein528 This is a mutation, though.

**Comment by onein528** [comment]
Right. How about implementing them in parallel? I said Mution will be get started v0.5 but I think newly we have to make what we have to implement on the page perfectly. When FluentHub become v0.4, I will be busy testing the safety of 'Query', and feel like i can't go v0.5 forever.

**Comment by DeveloperWOW64** [comment]
> Right. How about implementing them in parallel? I said Mution will be get started v0.5 but I think newly we have to make what we have to implement on the page perfectly. When FluentHub become v0.4, I will be busy testing the safety of 'Query', and feel like i can't go v0.5 forever.

Okay. Sure!

**Comment by DeveloperWOW64** [comment]
@onein528 Why the abandon?

**Comment by onein528** [comment]
This feature is couldn't implement.
