### ISSUE TITLE
Number normalizer

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#246]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

We might need count normalizer. If number is 40000 (as Star count), need to be 40k.

For example NuGet:

- DataSizeUnits

### 🗃️ Alternative solutions

No. Just add.

**Comment by DeveloperWOW64** [comment]
Ok. This shouldn't be *too* complex.

**Comment by onein528** [comment]
Yes. We shouldn't create it as a healer. Just should add as a library.

**Comment by onein528** [comment]
FluentHub should have an option of switching if you use normalized number or unnormanized number.

**Comment by DeveloperWOW64** [comment]
> FluentHub should have an option of switching if you use normalized number or unnormanized number.

@onein528 I'd say that's a bad idea. We'd have to worry even *more* than we already do on locale resources about text fitting if we gave an option that supported unnormalised number counts.

**Comment by onein528** [comment]
Wow that's way right. Thank you.
