### ISSUE TITLE
Empty space above notification on home page

### ISSUE THREAD

**Issue by hunterlan** [FluentHub/FluentHub#249]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11

### 🔢 What version/architecture of FluentHub are you on?

The last commit of main branch (01.09.2022) :D

### 📄 Description

On the screenshot below, you can see that the space between buttons and notification on home page is huge and empty. I see that it reserved for other section, but maybe it's better to hide it for a time. 

### 🤔 Expected behavior

Space between list of notifications and buttons will be lesser. 

### 📸 Assets

![image](https://user-images.githubusercontent.com/38838841/187972662-40deecfb-8da4-4d73-b1b4-b99af51cdb0c.png)

**Comment by DeveloperWOW64** [comment]
@hunterlan What branch are you building from?

**Comment by hunterlan** [comment]
> @hunterlan What branch are you building from?

I have a forked repo, which is syncing with main branch

**Comment by DeveloperWOW64** [comment]
@hunterlan Can you send a picture of the entire app window?

**Comment by DeveloperWOW64** [comment]
Ahh. This is a localisation error.

**Comment by DeveloperWOW64** [comment]
@hunterlan Use branch `localise`.

**Comment by hunterlan** [comment]
> @hunterlan Use branch `localise`.

Why?

**Comment by DeveloperWOW64** [comment]
> > @hunterlan Use branch `localise`.
> 
> Why?

Because that fixes the error.

**Comment by hunterlan** [comment]
> > > @hunterlan Use branch `localise`.
> > 
> > 
> > Why?
> 
> Because that fixes the error.

Oh, ok
But ```localise``` branch will not be always actual, right?

**Comment by DeveloperWOW64** [comment]
UserHomePage.xaml is relying on locale resources that don't exist in the `main` branch. However, those resources are implemented in #244, or `localise`.

**Comment by DeveloperWOW64** [comment]
> Oh, ok But `localise` branch will not be always actual, right?

Of course. Once all of FluentHub is successfully localised, we'll merge the PR and then you can use `main` correctly. For now, use `localise`.

**Comment by hunterlan** [comment]
> UserHomePage.xaml is relying on locale resources that don't exist in the `main` branch. However, those resources are implemented in #244, or `localise`.

Got it. So, we will not have a merge conflicts, when I will create PR

**Comment by DeveloperWOW64** [comment]
> > UserHomePage.xaml is relying on locale resources that don't exist in the `main` branch. However, those resources are implemented in #244, or `localise`.
> 
> Got it. So, we will not have a merge conflicts, when I will create PR

You can create it now if you like, #244 will take some time. @hunterlan

**Comment by DeveloperWOW64** [comment]
> > UserHomePage.xaml is relying on locale resources that don't exist in the `main` branch. However, those resources are implemented in #244, or `localise`.
> 
> Got it. So, we will not have a merge conflicts, when I will create PR

You can create a PR anytime! Don't worry about merge conflicts. @hunterlan
