### ISSUE TITLE
The about page doesn't work

### ISSUE THREAD

**Issue by arihant2math** [FluentHub/FluentHub#256]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11 Beta

### 🔢 What version/architecture of FluentHub are you on?

The about page doesn't work ...
v0.3.7

### 📄 Description

I cannot open the about page, it is shown as selected, but it does not change to the page.

### 🪜 Steps To Reproduce

1. Open the settings from the dropdown on the top right.
2. Click "About" on the bottom left.

### 🤔 Expected behavior

The about page should open properly.

### 📸 Assets

![image](https://user-images.githubusercontent.com/58895652/189572054-6ed468e7-9669-4e81-b67a-092c1461652e.png)

**Comment by onein528** [comment]
It should work in the latest store version v0.3.8.
