### ISSUE TITLE
Implement search functionality

### ISSUE THREAD

**Issue by arihant2math** [FluentHub/FluentHub#264]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

The search functionality in GitHub is probably going to be more used in fluent hub because people don't have google to search for projects on. I am implementing this with the [Octokit.net API](https://octokitnet.readthedocs.io/en/latest/search/). I will adhere to the GitHub search UI unless otherwise requested.

**Comment by onein528** [comment]
As you told, this feature is very important for FluentHub. So we need to discuss the matter about how we implement it.

**Comment by arihant2math** [comment]
@onein528 I am not so experienced with .NET design patterns, so ill need some help here, but the general idea is:
AutoSuggestBox (on type) -> return default set of suggestions (based on page)
SuggestionChosen or Submitted etc. -> navigate to a search page with a sidebar etc. (somehow communicating the searchbox value)

**Comment by onein528** [comment]
Currently, the former one would be nice.

**Comment by arihant2math** [comment]
The former as in?

**Comment by arihant2math** [comment]
@onein528 I have a couple of questions:

- What is the preferred way to store user data (from previous repo views etc.)
- What would be the preferred way to implement a sidebar nav for the search results?
- How would you check if the user is viewing a person, repo, or org?

**Comment by arihant2math** [comment]
I'm working on it:
![image](https://user-images.githubusercontent.com/58895652/190927570-53eb2441-f200-46e6-bdde-4c0efc4c5324.png)

**Comment by arihant2math** [comment]
@onein528 I'll need icons for the stuff with notification icons on them.

**Comment by onein528** [comment]
Ah, I'm not sure Octokit.NET has search APIs.

**Comment by onein528** [comment]
1. maybe json file with something service.
2. shouldn't be NavigationView. I think it should just be button group.
3. hmm. title? like 'search result on FluentHub/FluentHub repository'

**Comment by arihant2math** [comment]
It has some of them: 
[https://octokitnet.readthedocs.io/en/latest/search/](https://octokitnet.readthedocs.io/en/latest/search/)

**Comment by onein528** [comment]
> @onein528 I'll need icons for the stuff with notification icons on them.

You can get them from Assets/Icons/**

**Comment by onein528** [comment]
> It has some of them: 
> [https://octokitnet.readthedocs.io/en/latest/search/](https://octokitnet.readthedocs.io/en/latest/search/)

wow really cool.

**Comment by arihant2math** [comment]
> > @onein528 I'll need icons for the stuff with notification icons on them.
> 
> You can get them from Assets/Icons/**

Some of them don't have icons in that folder. Check the mock-up for the stuff that I can't find icons for.

**Comment by onein528** [comment]
Wiki

![image](https://user-images.githubusercontent.com/62196528/190939959-7f690c5a-57e5-4ae4-a6bf-e6540e263a5b.png)

Code

![image](https://user-images.githubusercontent.com/62196528/190940018-1db9f0ef-6330-48c5-8045-6d50d09573c0.png)

Marketplace

![image](https://user-images.githubusercontent.com/62196528/190940116-752094a7-d283-41ce-9e2f-3931454f1056.png)

Topic

![image](https://user-images.githubusercontent.com/62196528/190940174-42c1dab4-36de-439d-bf51-9f4739c698c1.png)

**Comment by onein528** [comment]
How about? @arihant2math

**Comment by arihant2math** [comment]
Icons lgtm, ill add them.

**Comment by arihant2math** [comment]
@onein528 How about the tab icon? It is currently the settings icon, but it needs to be changed.

**Comment by DeveloperWOW64** [comment]
> @onein528 How about the tab icon? It is currently the settings icon, but it needs to be changed.

Changed to what @arihant2math?

**Comment by onein528** [comment]
Find icon:

![image](https://user-images.githubusercontent.com/62196528/191203988-07627f53-7277-4da5-94c1-7f2f2817404e.png)

**Comment by arihant2math** [comment]
@onein528 I need one more icon for discussions. Thanks for the icons

**Comment by DeveloperWOW64** [comment]
> @onein528 I need one more icon for discussions. Thanks for the icons

![image](https://user-images.githubusercontent.com/71598437/191430720-d26dd294-e622-4770-87aa-9d8b893a774d.png)

**Comment by onein528** [comment]
the one that he showed @DeveloperWOW64 is already included in fluenthub. what do you mean more icons for discussion? id like to ask why do you need more icons than one for one meaning thing?

**Comment by arihant2math** [comment]
@onein528 My bad, I didn't realize that the icon was there.

**Comment by arihant2math** [comment]
@onein528 Due to all those complications I lost all the code that was on git, I still have the code on my local machine though, so I'll have to destroy my fork, create a new one, and the reupload it all.

**Comment by onein528** [comment]
Could you wait a few days for doing that? @arihant2math

**Comment by onein528** [comment]
@arihant2math

**Comment by arihant2math** [comment]
![image](https://user-images.githubusercontent.com/58895652/192126790-00284432-7a79-4e59-8488-ef3f271d9216.png)
I saw only 3 commits on that branch, the bulk of the code was missing, since it was all deleted, now I am going through and carefully recreating the code.

**Comment by onein528** [comment]
Your branch name is updated to search2. and re-invited you.

**Comment by arihant2math** [comment]
The branch actually doesn't build because I messed up the .csproj file too much. I think I'll work on the normal branch because it seems you have moved the changes there.

**Comment by DeveloperWOW64** [comment]
> The branch actually doesn't build because I messed up the .csproj file too much. I think I'll work on the normal branch because it seems you have moved the changes there.

'normal branch' wdym? @arihant2math

**Comment by arihant2math** [comment]
the default search branch

**Comment by onein528** [comment]
@arihant2math Done first step. Can you open a PR with this branch?

[Open a PR](https://github.com/FluentHub/FluentHub/compare/main...search)

![image](https://user-images.githubusercontent.com/62196528/192306259-851cbbf1-9626-4340-b5da-c9e2a532ed0a.png)
