### ISSUE TITLE
Label Pills

### ISSUE THREAD

**Issue by arihant2math** [FluentHub/FluentHub#303]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

Added support for colored pills to surround issue and pr labels.

**Comment by onein528** [comment]
What is the 'Pills'?

**Comment by arihant2math** [comment]
Like the blue ellipse around the feature request label

**Comment by DeveloperWOW64** [comment]
> Like the blue ellipse around the feature request label

Don't we already have this?

**Comment by onein528** [comment]
Yes Already have it.
