### ISSUE TITLE
Azure Pipelines doesn't publish build artifacts

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#324]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11

### 🔢 What version/architecture of FluentHub are you on?

_None_

### 📄 Description

As the title

### 🤔 Expected behavior

Publish build artifacts

### 📟 Stack Trace

_None_

### 📸 Assets

_None_

**Comment by onein528** [comment]
https://dev.azure.com/fluenthub/FluentHub/_build/results?buildId=1673&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by DeveloperWOW64** [comment]
> Azure Pipelines doesn't publish build artifacts
I noticed this before..

**Comment by onein528** [comment]
What. Really? Then, I forgot that and I will investigate this problem.

**Comment by onein528** [comment]
Why is it so difficult to find important information from Microsoft Docs?

![image](https://user-images.githubusercontent.com/62196528/196235541-7f40174f-0eb7-41e8-981f-be85a2c5df76.png)

**Comment by Lamparter** [comment]
#253 #486
