### ISSUE TITLE
Animate NavigationViewItems Icons

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#330]
### 🛤️ Feature
Animate NavigationViewItems icons.

### 📄 Description
Animates NavigationViewItem icons found in the NavigationViewItem model. This may require utilisation of the Windows Lottie Animation API or similar, as directly implementing a video of an animated icon may be difficult. Animated/non-animated icons can be found in the `📸 Assets` section.

### 📸 Assets
**Home**
*`Not yet animated`*
![house-with-garden_1f3e1](https://user-images.githubusercontent.com/71598437/197329698-21086d4d-017d-4e95-8622-37ca3381005a.png)

**Notifications**
*`Undecided`*
1.
![alarm-clock_23f0](https://user-images.githubusercontent.com/71598437/197329849-d8214ab3-af8f-4740-8d03-669a3f7040d6.png)
![alarm_clock_3d](https://user-images.githubusercontent.com/71598437/197329908-38792d1b-3e59-475d-842b-7317e5f5f117.png)
2.
*`Not yet animated`*
![bell_1f514](https://user-images.githubusercontent.com/71598437/197329923-a281cd38-9c73-469e-929a-3f7d82364f0c.png)

**Activities**
![fire_1f525](https://user-images.githubusercontent.com/71598437/197329964-56cdfae8-10ed-4d32-9edc-7f09bffc7152.png)
![fire_3d](https://user-images.githubusercontent.com/71598437/197329988-47b09c92-a3f3-4c7b-8b27-e5541f0f8817.png)

**Profile**
![](https://emojipedia-us.s3.amazonaws.com/source/microsoft-teams/337/person-raising-hand_1f64b.png)
![person_raising_hand_3d_default](https://user-images.githubusercontent.com/71598437/197330067-c5380398-800c-4365-a247-dd7b3487a3d3.png)

**Comment by onein528** [comment]
I've never gone through this implementation. So may take a long time.

**Comment by DeveloperWOW64** [comment]
> **Home**
 _`Not yet animated`_
![house-with-garden_1f3e1](https://user-images.githubusercontent.com/71598437/197329698-21086d4d-017d-4e95-8622-37ca3381005a.png)

Only problem with this is that animated version does not exist.

**Comment by onein528** [comment]
Outdated.
