### ISSUE TITLE
Bug: Null reference exception in home

### ISSUE THREAD

**Issue by arihant2math** [FluentHub/FluentHub#335]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11 Beta

### 🔢 What version/architecture of FluentHub are you on?

0.5.0 x64

### 📄 Description

When the app has a code or xaml error, the error page does not load, instead the app crashes. This was caused by the wsasdk migration.

### 🤔 Expected behavior

The normal error page shows up

### 📟 Stack Trace

<details><summary>Stack trace details</summary><div>

```
Cannot get one
```

</div></details>

**Comment by arihant2math** [comment]
I can try sending in a pr if it is not a wsasdk limitation

**Comment by onein528** [comment]
I don't think it is WASDK limitations - there's no such an issue filed. Also I didn't know what this is.

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2022-11-09 110210](https://user-images.githubusercontent.com/52818836/200772844-abf02584-322f-44f6-a248-fc1b3b3b868a.png)
🤔

**Comment by onein528** [comment]
v5 is already published in the Store
