### ISSUE TITLE
Why use Windows App SDK

### ISSUE THREAD

**Issue by wherewhere** [FluentHub/FluentHub#350]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11 Dev

### 🔢 What version/architecture of FluentHub are you on?

0.5.0.0 | X64 | RELEASE

### 📄 Description

It is just a client of Github. It does not need any win32 permision. Why use Windows App SDK. It does't support Xbox/Hub/Hololens. And the dpi is soo weird. Please bring back UWP!!!

### 🤔 Expected behavior

It should be UWP and support Xbox/Hub/Hololens

### 📟 Stack Trace

<details><summary>Stack trace details</summary><div>

```
paste here
```

</div></details>

### 📸 Assets

Bad dpi
![image](https://user-images.githubusercontent.com/27689196/204426744-b5497e6a-3998-4ee8-918a-62090ff3cde1.png)
![image](https://user-images.githubusercontent.com/27689196/204426986-33f91796-cd09-466e-8c22-6c7ee3cceb5e.png)

**Comment by onein528** [comment]
There're advantages of using of it.

- Reduce building time significantly.
- Full support of WebView2
- Reorganized namespaces

Disadvantages.

- Little but unstable.


As @DeveloperWOW64 have told you already,  WASDK is being made it like it is the next generation of UWP.

I've never heard of the issue of low dpi, so it seems to be very difficult to solve. DPI issue, however, will be fixed in the future release.

**Comment by wherewhere** [comment]
Next generation? Have you see any inbox app use WAS? WAS is a win32 platform. It have full access to any permission. The permission manager of App content become a decoration. The most important thing is WAS is not universe anymore. It will never be the next generation of UWP.

**Comment by wherewhere** [comment]
The dpi problem seems caused by .net7. I meet one time when I target a WPF project to net7. You can try to set scaling to 150%.

**Comment by Lightczx** [comment]
@onein528  Include an `app.manifest` shown below can resolve dpi issue.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity version="1.0.0.0" name="Snap.Hutao.app"/>

  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <!-- The combination of below two tags have the following effect:
           1) Per-Monitor for >= Windows 10 Anniversary Update
           2) System < Windows 10 Anniversary Update
      -->
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
    </windowsSettings>
  </application>
</assembly>
```

The manifest is included automatically when you create a winui3 project.
And the .csproj file may change a little bit too.

``` xml
<PropertyGroup>
  <ApplicationManifest>app.manifest</ApplicationManifest>
</PropertyGroup>
```

**Comment by onein528** [comment]
Opps. I thought this is extra file, and I will add it. tnx

**Comment by onein528** [comment]
UWP is outdated technology. And WASDK is defined as a new generation of UWP even if it is still under development and unstable.

I'll fix DPI problem by adding the workaround code in app.manifest
