### ISSUE TITLE
Bug: Issue and PR comment content can't be loaded

### ISSUE THREAD

**Issue by NalCol** [FluentHub/FluentHub#357]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11 Beta

### 🔢 What version/architecture of FluentHub are you on?

0.5.0.0 | X64 | RELEASE

### 📄 Description

Issue's Markdown text block/reply will be empty after loaded.
See the image provided in asset section.

### 🪜 Steps To Reproduce

1. Go on any issue page
2. See if the issue's content show up correctly

### 🤔 Expected behavior

Show Markdown Text correctly

### 📟 Stack Trace

Not provided.
<details><summary>Stack trace details</summary><div>

```
paste here
```

</div></details>

### 📸 Assets

![image](https://user-images.githubusercontent.com/58576200/209125122-b6e3187b-7e82-43f4-82a0-c227101a67f1.png)

**Comment by onein528** [comment]
That's related WebView2 issues. Tracking.

**Comment by 0x5bfa** [comment]
This was fixed in the latest release v0.8.9(not supporting markdown natively yet though).
Thank you!
