### ISSUE TITLE
Bug: Cannot login to FluentHub via GitHub

### ISSUE THREAD

**Issue by TotoWang-hhh** [FluentHub/FluentHub#361]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 10 Beta | X64

### 🔢 What version/architecture of FluentHub are you on?

v0.5.0

### 📄 Description

When I press `Login with GitHub`, my  browser started automatically, and I authorized this application. Then the app didn't make any changes when I pressed 'open' in my browser

### 🤔 Expected behavior

FluentHub will login

### 📟 Stack Trace

NO ERROR

<details><summary>Stack trace details</summary><div>

```
paste here
```

</div></details>

**Comment by kengwang** [comment]
I noticed that you are probably in China and using proxy to access GitHub.
As FluentHub is and UWP application, it cannot access your local proxy unless you enable loopback for FluentHub
Just simple run the command below in either cmd or PowerShell
```
CheckNetIsolation Loopbackexempt -a -n="49462fluenthub-uwp.fluenthub_tq8wa33sfftnm"
```

Then you can login to FluentHub

**Comment by onein528** [comment]
@TotoWang-hhh That was useful to you?

**Comment by TotoWang-hhh** [comment]
> @TotoWang-hhh That was useful to you?

It may be a network problem. I logged in succsessful a few days later
