### ISSUE TITLE
I can't create a new repository.

### ISSUE THREAD

**Issue by arduinoclassroom** [FluentHub/FluentHub#370]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11

### 🔢 What version/architecture of FluentHub are you on?

Windows Version: 11

### 📄 Description

I got Microsoft Store's Fluent Hub app. And I'm signed in to it. But I need help creating a new repository. Because the button to create a new repository is disabled.
Look this image.
![image](https://user-images.githubusercontent.com/92985498/216752918-cc0e96cf-f4ac-411b-82cd-d99fae7aee2c.png)

### 🤔 Expected behavior

![image](https://user-images.githubusercontent.com/92985498/216752998-885bc942-0015-4f91-9ded-fe431ebca130.png)

### 📟 Stack Trace

<details><summary>Stack trace details</summary><div>

![image](https://user-images.githubusercontent.com/92985498/216752964-1418880a-a15b-464d-aee5-2ef82c2e9952.png)

</div></details>

### 📸 Assets

![image](https://user-images.githubusercontent.com/92985498/216752977-8fb09e28-512f-4f40-95bb-de490e7a31bf.png)

**Comment by MetropolitanCitizen** [comment]
Hello @arduinoclassroom!
I'm a member of the @FluentHub/team and I'm here to help.

FluentHub does not yet support the creation of repositories. That button will remain there for future notice until the feature is implemented. Thank you.
