### ISSUE TITLE
Fix: Blurry texts and icons in a high DPI screen

### ISSUE THREAD

**Issue by hujiadfr** [FluentHub/FluentHub#385]
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11 Beta

### 🔢 What version/architecture of FluentHub are you on?

0.5.0.0 | X64 | RELEASE

### 📄 Description

The program is blurry in a hidpi screen(3072x1920 200% scaling).
![屏幕截图 2023-04-15 164704](https://user-images.githubusercontent.com/55337375/232202621-16feebfc-d6d7-47e3-8dd4-f807f9f77cd3.png)

### 🪜 Steps To Reproduce

Open FluentHub in a hidpi monitor.

### 🤔 Expected behavior

Fonts and icons need to be clearly displayed

### 📟 Stack Trace

<details><summary>Stack trace details</summary><div>

```
paste here
```

</div></details>

**Comment by Lamparter** [comment]
Hi @hujiadfr!
Are you using the version of FluentHub downloaded from the Microsoft Store?

**Comment by hujiadfr** [comment]
Yes, I download it from the Microsoft Store. I also try to build it myself(commit hash: 9c78148e5e4021ef3c3c06dc1e57714ebe24dae0) but it has the same bug.

**Comment by Lamparter** [comment]
> Yes, I download it from the Microsoft Store. I also try to build it myself(commit hash: [9c78148](https://github.com/FluentHub/FluentHub/commit/9c78148e5e4021ef3c3c06dc1e57714ebe24dae0)) but it has the same bug.

Funny, I thought we'd fixed this bug in the latest version.
