### ISSUE TITLE
Bug: The window is blurred on high DPI screen

### ISSUE THREAD

**Issue by ShenMian** [FluentHub/FluentHub#405]
### Before you start

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 11

### What version/architecture of FluentHub are you on?

0.5.0.0 | X64 | RELEASE

### Description

Desktop mode resolution: 2560x1440.
The content of the form is not clear.

(There are also very frequent crashes, but I currently don't know how to report such issues)

### Expected behavior

Content should be clear.

### Stack Trace

<details><summary>Stack trace details</summary><div>

```
no crash
```

</div></details>

### 📸 Assets

<img width="950" alt="image" src="https://github.com/FluentHub/FluentHub/assets/70068015/5ddb2c08-978c-4d04-b2dd-e0358579a868">

**Comment by 0x5bfa** [comment]
Thank you for feedback.

This was fixed in v5.0.1
