### ISSUE TITLE
Bug: Crashes when the token has been revoked

### ISSUE THREAD

**Issue by zyxeeker** [FluentHub/FluentHub#408]
### Before you start

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 10

### What version/architecture of FluentHub are you on?

V0.5.0 RELEASE

### Description

 Reopen it or browse repo will crashed after I revoke authorization from GitHub.

### Steps To Reproduce

1. Authorize app
2. Revoke authorization
3. Reopen app or browse repo

### Expected behavior

Ensure do not occur such a problem.

### Stack Trace

Not show error page

**Comment by 0x5bfa** [comment]
Thank you for feedback.

**Comment by 0x5bfa** [comment]
I uploaded the new version 0.8.9 into the Store. Can you check if this issue still exists?

**Comment by zyxeeker** [comment]
i will check it, thanks

**Comment by 0x5bfa** [comment]
Crashing should be fixed in 0.8.40 Can you fix?

I will add more detailed message for it in the future.

**Comment by zyxeeker** [comment]
> Crashing should be fixed in 0.8.40 Can you check?
> 
> I will add more detailed message for it in the future.

sorry, i find my reply had not been sent. i will check it in my spare time

**Comment by zyxeeker** [comment]
the problem is fixed, thanks
