### ISSUE TITLE
Add Discussion and Project tabs into top bar

### ISSUE THREAD

**Issue by NalCol** [FluentHub/FluentHub#411]
### Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### Description

Remove old discussion and project page design and make these tabs into top bar.

Now we have 2 bars on same page!

See picture below.

### Assets

![image](https://github.com/FluentHub/FluentHub/assets/58576200/e7e0f8f9-1379-4d0e-a748-20873382325a)

**Comment by 0x5bfa** [comment]
Thank you for the feedback. I will do that in the next release!

**Comment by 0x5bfa** [comment]
Added in 0.8.40
