### ISSUE TITLE
Feature: Add icons to the NavigationBar items

### ISSUE THREAD

**Issue by NalCol** [FluentHub/FluentHub#412]
### Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### Description

Now items in top bar (Code, Issues, PRs) don't have **icons** and **counters**

Old page design do have them

Considering to add them back?

### Assets

![image](https://github.com/FluentHub/FluentHub/assets/58576200/77dbabf8-8273-42df-bcb5-8107b45dcd32)

**Comment by 0x5bfa** [comment]
Thank you for the feedback.
That’s actually hard work a bit but I will do that soon!

**Comment by 0x5bfa** [comment]
Added in the latest commit. Thanks!

**Comment by 0x5bfa** [comment]
![image](https://github.com/FluentHub/FluentHub/assets/62196528/6218b7d0-851e-410a-a7bd-4b92c6c50945)
