### ISSUE TITLE
Add multi-account support

### ISSUE THREAD

**Issue by BobbyESP** [FluentHub/FluentHub#8]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

As the title

**Comment by onein528** [comment]
Yeah, it's good idea.

**Comment by BobbyESP** [comment]
Yes, and i think it's a very simple integration. Creating a local JSON file or XML with the multiple accounts and access token

**Comment by onein528** [comment]
or [user app settings container](https://docs.microsoft.com/en-us/windows/uwp/get-started/settings-learning-track)

**Comment by BobbyESP** [comment]
Oh, that's nice!

**Comment by BobbyESP** [comment]
ADVISEMENT: This feature will be included in next updates. Due to the final exams at my school, i won't be able to work on it until 6th of June. Sorry for the inconveniences.
